RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "The Trainer's School is excellent.\p"
	.string "Though the teacher likes using\n"
	.string "Quick Claws as punishment.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Farfa, the Gym Leader, really knows\n"
	.string "a lot about Burning Abyss.\p"
	.string "Not so much about math.$"

