LilycoveCity_MuttHouse_MapScripts::
	.byte 0

LilycoveCity_MuttHouse_EventScript_GachaSimp::
	msgbox LilycoveCity_MuttHouse_Text_Hutt, MSGBOX_NPC
	end

LilycoveCity_MuttHouse_EventScript_Firefly::
	msgbox LilycoveCity_MuttHouse_Text_Simp, MSGBOX_SIGN
	end

LilycoveCity_MuttHouse_Text_Hutt:
	.string "All Marincess needs is a\n"
	.string "Dragoon bro, trust.$"

LilycoveCity_MuttHouse_Text_Simp:
	.string "Some kind of RPG is being played.\p"
	.string "The active party member is saying\n"
	.string "something about setting seas ablaze.$"

