gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\n"
	.string "Welcome to Pokémon Unchained Emerald!\p"
	.string "This is a hack made by members\n"
	.string "of DistantCoder's community.\l"
	.string "And a little outsourcing.\p"
	.string "A huge thank you goes out to:\p"
	.string "DeckDevil, Mutthunter, Duckie, Ant,\n"
	.string "Refisio, Souls and Fyre.\l"
	.string "Oh, and I guess the team lead.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Aipom jumpscare.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This hack's official release was made\n"
	.string "specially for Coder's 5th Subathon.\p"
	.string "There's brand-new Pokémon that\n"
	.string "Emerald normally wouldn't have.\p"
	.string "A collection of familiar faces,\n"
	.string "and a whole lot more to find.\p"
	.string "You'll have to discover the rest\n"
	.string "on your own terms.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oh, yes, almost forgot.$"

gText_Birch_BoyOrGirl::
	.string "M Coder?\n"
	.string "Or F Coder?$"

gText_Birch_WhatsYourName::
	.string "I see.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "the town of Littleroot.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I hope you enjoy the adventure\n"
	.string "that we laid out for you.\p"
	.string "There's a lot to look out for!\p"
	.string "Alright, I'll meet you soon.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
