gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\n"
	.string "Welcome to Pokémon Millennium Emerald!\p"
	.string "This is a hack to mix up the\n"
	.string "Hoenn region a little bit.\p"
	.string "This has been quite the project,\n"
	.string "so some shoutouts are in order.\p"
	.string "A huge thank you goes out to:\n"
	.string "DeckDevil, Mutthunter, Duckie, Ant,\l"
	.string "Refisio, Souls and Fyre.\p"
	.string "$"

gText_Birch_Pokemon:: @this is unused, refer to gText_ThisIsAPokemon
	.string "Applaud them or die.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This hack was designed specifically\n"
	.string "with the Yu-Gi-Oh community in mind.\p"
	.string "There's brand-new Pokémon that\n"
	.string "Emerald normally wouldn't have.\p"
	.string "A collection of familiar faces,\n"
	.string "and a whole lot more to find.\p"
	.string "You'll have to discover the rest\n"
	.string "on your own terms.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oh, yes, almost forgot.$"

gText_Birch_BoyOrGirl::
	.string "You playing as a boy?\n"
	.string "Or as a girl?$"

gText_Birch_WhatsYourName::
	.string "I see.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "the town of Littleroot.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I hope you enjoy the adventure\n"
	.string "that we laid out for you.\p"
	.string "There's a lot to look out for!\p"
	.string "Alright, I'll meet you soon.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
