MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Whoo!\p"
	.string "I love aerodynamics!\p"
	.string "I bet your Pokémon would too!\p"
	.string "If you'd like, I'll teach one of\n"
	.string "them the move Air Cutter!$"

MoveTutor_Text_SwaggerDeclined:
	.string "What? No aerodynamics?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to cut the air?$"

MoveTutor_Text_SwaggerTaught:
	.string "Yeah! Air!$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction?\p"
	.string "I might even be able to roll\n"
	.string "all that way.\p"
	.string "Do you think your Pokémon will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move Rollout\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the Pokémon looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's pretty wicked.\n"
	.string "The move's Fury Cutter.\p"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move Mimic?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach Mimic\n"
	.string "to your Pokémon!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the Pokémon\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "Mimic is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Wouldn't it be nice if you could\n"
	.string "call RNG by waggling a finger?\p"
	.string "If you want, I can teach your Pokémon\n"
	.string "the move Metronome.$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind or finger.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a Pokémon waggles its finger\n"
	.string "like a Metronome, a shitshow happens.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "My wife and I share our grievances\n"
	.string "with each other.\p"
	.string "It could be considered a split\n"
	.string "of our pain.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Pain Split too. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You hate division.$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an understanding child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I split that pain with her too.$"

MoveTutor_Text_SubstituteTeach:
	.string "If I dropped something here, it would\n"
	.string "never reach terminal velocity.\p"
	.string "The gravity here isn't strong enough.\p"
	.string "Though I could teach one of your\n"
	.string "Pokémon how to increase Gravity.$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no!\p"
	.string "Anyway.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\p"
	.string "Which Pokémon do you want me to\n"
	.string "troll Isaac Newton with?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Hahaha!\p"
	.string "A resounding victory!\p"
	.string "I like to use Fighting types,\n"
	.string "so Mossdeep Gym is a breeze!\p"
	.string "My special technique is all\n"
	.string "that I need!\p"
	.string "Shall I teach your Pokémon\n"
	.string "the move DynamicPunch?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Fine, I'll keep it to myself!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "You do? Good decision!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that DynamicPunch!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Sootopolis' Gym Leader is really\n"
	.string "incredible.\p"
	.string "She's really great with her team\n"
	.string "of Grass types.\p"
	.string "But I know a move that Grass types\n"
	.string "can't handle very well.\p"
	.string "Shall I teach a Pokémon how to\n"
	.string "use the move Gunk Shot?$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "No garbage gaming then.$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which Pokémon should I teach\n"
	.string "Gunk Shot?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Dumpster diving!$"

MoveTutor_Text_ExplosionTeach:
	.string "I AM GOING TO EXPLODE.\p"
	.string "WOULD ONE OF YOUR COMPANIONS\n"
	.string "LIKE TO EXPLODE?$"

MoveTutor_Text_ExplosionDeclined:
	.string "DETONATION SEQUENCE STALLED.$"

MoveTutor_Text_ExplosionWhichMon:
	.string "EXCELLENT.$"

MoveTutor_Text_ExplosionTaught:
	.string "TIME TO EXPLODE.$"
