Route102_Text_CalvinIntro:
	.string "Haha! You shall fall to an\n"
	.string "8 year old!$"

Route102_Text_CalvinDefeated:
	.string "Adults are scary.$"

Route102_Text_CalvinPostBattle:
	.string "You'd better not lose to\n"
	.string "a 9 year old!$"

Route102_Text_CalvinRegister:
	.string "Oh hey, a Nav!\n"
	.string "Curse of little shit$"

Route102_Text_CalvinRegisterShort:
	.string "Oh hey, a Nav!\n"
	.string "Curse of little shit$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my Pokémon.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, I lost…\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you're going to get stronger,\n"
	.string "I'll get stronger, too.$"

Route102_Text_AllenIntro:
	.string "Did you just become a Trainer?\n"
	.string "We're both noobs!$"

Route102_Text_AllenDefeated:
	.string "I called you because I thought\n"
	.string "I could beat you…$"

Route102_Text_AllenPostBattle:
	.string "I haven't won once yet…\n"
	.string "I'm just a bye…$"

Route102_Text_RickIntro:
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my Inzektors!$"

Route102_Text_RickDefeated:
	.string "Ow! Handtrapped!$"

Route102_Text_RickPostBattle:
	.string "If you lock eyes with a Trainer,\n"
	.string "you have to go first! It's a rule!$"

Route102_Text_TianaIntro:
	.string "I'm going to keep winning and aim\n"
	.string "to be the best Trainer.\p"
	.string "Help me further my career!$"

Route102_Text_TianaDefeated:
	.string "I ended up furthering your career…$"

Route102_Text_TianaPostBattle:
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more Pokémon.$"

Route103_Text_DaisyIntro:
	.string "Did you feel the tug of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_DaisyDefeated:
	.string "You weren't led astray by our aroma…$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_AmyIntro:
	.string "Amy: I'm Amy.\n"
	.string "And this is my little sister Liv.\l"
	.string "We battle together!$"

Route103_Text_AmyDefeated:
	.string "Amy: Uh-oh, we lost.$"

Route103_Text_AmyPostBattle:
	.string "Amy: You have to think about all\n"
	.string "kinds of things with double battles.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "Amy: Uh-oh, you have only one\n"
	.string "Pokémon with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivIntro:
	.string "Liv: We battle together as one\n"
	.string "team.$"

Route103_Text_LivDefeated:
	.string "Liv: Oh, we lost, big sister…$"

Route103_Text_LivPostBattle:
	.string "Liv: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: If you want to battle us,\n"
	.string "you have to have two Pokémon!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, boo!\n"
	.string "We couldn't win again…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "Amy: Uh-oh, you have only one\n"
	.string "Pokémon with you.\l"
	.string "You must be lonely.$"

Route103_Text_LivRematchIntro:
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "Liv: If you want to battle us, you\n"
	.string "have to have two Pokémon!$"

Route103_Text_AndrewIntro:
	.string "Gah! My Buzzsaw line's all snarled up!\n"
	.string "I'm getting frustrated and mean!\l"
	.string "That's it! Battle me!$"

Route103_Text_AndrewDefeated:
	.string "Gah! Lost it!\n"
	.string "I'm even more annoyed now!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, I'm passing turn…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "My Pokémon is delightfully adorable!\n"
	.string "Don't be shy--I'll show you!$"

Route103_Text_MiguelDefeated:
	.string "Oh, my gosh!\n"
	.string "My darling Pokémon!$"

Route103_Text_MiguelPostBattle:
	.string "My delightful Pokémon looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_MiguelRegister:
	.string "I'll get you to come out and look in\n"
	.string "on my delightful Pokémon again!$"

Route103_Text_MiguelRematchIntro:
	.string "Hi, you! My delightfully adorable\n"
	.string "Pokémon has become more darling!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "My darling Pokémon!$"

Route103_Text_MiguelRematchPostBattle:
	.string "The more I spend time with it,\n"
	.string "the more adorable my Pokémon becomes.$"

Route103_Text_PeteIntro:
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_PeteDefeated:
	.string "Oh, that's good going!$"

Route103_Text_PetePostBattle:
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "You forgot your swimming gear!$"

Route103_Text_IsabelleIntro:
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_IsabelleDefeated:
	.string "Groan…$"

Route103_Text_IsabellePostBattle:
	.string "Seems like you had more ATK.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "How'd you get into a space this small?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "They can Nib!$"

Route103_Text_RhettPostBattle:
	.string "Do you like cramped quarters\n"
	.string "like this?\p"
	.string "Reminds me of locals.$"

Route103_Text_MarcosIntro:
	.string "Did my guitar's wailing draw you in?$"

Route103_Text_MarcosDefeated:
	.string "My one-man show is ruined…$"

Route103_Text_MarcosPostBattle:
	.string "Now I'm wailing.$"

Route104_Text_GinaIntro:
	.string "Gina: Okay, let's battle with our\n"
	.string "Pokémon!$"

Route104_Text_GinaDefeat:
	.string "Gina: Losing upsets me!$"

Route104_Text_GinaPostBattle:
	.string "Gina: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_GinaNotEnoughMons:
	.string "Gina: Oh? Only one Pokémon?\n"
	.string "Then, we don't battle with you.\p"
	.string "If there's only one Pokémon, it will\n"
	.string "be lonesome. That's not nice.$"

Route104_Text_MiaIntro:
	.string "Mia: We are twins, so we battle\n"
	.string "Pokémon together.$"

Route104_Text_MiaDefeat:
	.string "Mia: We battled together, but we\n"
	.string "both lost…$"

Route104_Text_MiaPostBattle:
	.string "Mia: We will train our Pokémon more\n"
	.string "and be strong like you.$"

Route104_Text_MiaNotEnoughMons:
	.string "Mia: You want to battle with us?\p"
	.string "It's a big no-no if you don't have two\n"
	.string "Pokémon with you.\l"
	.string "We're too strong for you!$"

Route104_Text_IvanIntro:
	.string "Why keep it a secret?\n"
	.string "I'm the Mermail expert!\p"
	.string "Huh?\n"
	.string "You don't know Heavy Infantry?$"

Route104_Text_IvanDefeat:
	.string "I thought I wasn't too bad, but I\n"
	.string "forgot to detach…$"

Route104_Text_IvanPostBattle:
	.string "I got too into fishing.\n"
	.string "I forgot I had to rarity bump…$"

Route104_Text_BillyIntro:
	.string "Leaving footprints in the sand is\n"
	.string "so fun!$"

Route104_Text_BillyDefeat:
	.string "Waah! I got sand in my runners!\n"
	.string "They're all gritty!$"

Route104_Text_BillyPostBattle:
	.string "I want to leave my footprints in\n"
	.string "the sand everywhere, but they\l"
	.string "disappear quickly…$"

Route104_Text_HaleyIntro:
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will netdeck!$"

Route104_Text_HaleyDefeat:
	.string "I shouldn't have netdecked…$"

Route104_Text_HaleyPostBattle:
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for you,\l"
	.string "they should choose the funny option.$"

Route104_Text_HaleyRegister1:
	.string "You're strong, but should I register\n"
	.string "you in my Pokénav?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRegister2:
	.string "You're strong, but should I register\n"
	.string "you in my Pokénav?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_HaleyPostRematch:
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro:
	.string "Oh, sure, I'll accept your challenge.\n"
	.string "I have every Number in max rarity.$"

Route104_Text_WinstonDefeat:
	.string "Why couldn't I win?\n"
	.string "I bought max rarity Snake-Eyes too!$"

Route104_Text_WinstonPostBattle:
	.string "There are some things money can't buy.\n"
	.string "But it can buy SJC Crush Card Virus.$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, you've obtained a Pokénav.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, you've obtained a Pokénav.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRematchIntro:
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about Pokémon.$"

Route104_Text_WinstonRematchDefeat:
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch:
	.string "I'm fabulously wealthy, but I can't\n"
	.string "seem to win at Pokémon…\p"
	.string "It's so deep, the world of Pokémon…$"

Route104_Text_CindyIntro:
	.string "We must have been fated to meet.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyDefeat:
	.string "Oh, my!$"

Route104_Text_CindyPostBattle:
	.string "“H” is the beginning of “Heroic.”\n"
	.string "Rhongo bongo.$"

Route104_Text_CindyRegister1:
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our PokénavS.$"

Route104_Text_CindyRegister2:
	.string "We should commemorate how we seem\n"
	.string "to be drawn to each other.\p"
	.string "Let's register each other in our\n"
	.string "PokénavS.$"

Route104_Text_CindyRematchIntro:
	.string "Hello, we meet again.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, my…\n"
	.string "I did the best that I could…$"

Route104_Text_CindyPostRematch:
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

Route104_Text_DarianIntro:
	.string "Ah, so you've chosen to battle me.\p"
	.string "It seems you aren't familiar with\n"
	.string "the strength of my Pokémon.\p"
	.string "Well, time to cause another incident.$"

Route104_Text_DarianDefeat:
	.string "What the…$"

Route104_Text_DarianPostBattle:
	.string "Consider me impressed.\p"
	.string "I traumatized one of the\n"
	.string "developers once.$"

Route105_Text_FosterIntro:
	.string "There's supposed to be a mystical\n"
	.string "rock around here.\l"
	.string "Do you know anything about it?$"

Route105_Text_FosterDefeated:
	.string "I was thinking too much about that\n"
	.string "rock, and you flipped TCBOO…$"

Route105_Text_FosterPostBattle:
	.string "I can spend hours and hours staring\n"
	.string "at a nice rock without growing bored.$"

Route105_Text_LuisIntro:
	.string "I was worried there was someone\n"
	.string "drowning when I saw you.\p"
	.string "You seem to be okay, so what do you\n"
	.string "say to a battle?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "If you are drowning, the signal is to\n"
	.string "wave one arm toward the beach.$"

Route105_Text_DominikIntro:
	.string "Swimming the deep blue sea…\n"
	.string "It feels the greatest!$"

Route105_Text_DominikDefeated:
	.string "I lost…\n"
	.string "Now I'm feeling blue…$"

Route105_Text_DominikPostBattle:
	.string "Why is the sea blue?\p"
	.string "I dunno.$"

Route105_Text_BeverlyIntro:
	.string "My body feels lighter in the water.\n"
	.string "It's as if I've gotten slimmer!$"

Route105_Text_BeverlyDefeated:
	.string "I'm floating…$"

Route105_Text_PostBattle:
	.string "Your body weight is reduced to just\n"
	.string "one tenth in the water.\p"
	.string "That would make me…\n"
	.string "Radioactive!$"

Route105_Text_ImaniIntro:
	.string "The blue, blue sky…\n"
	.string "The vast sea…\l"
	.string "It's so peaceful…$"

Route105_Text_ImaniDefeated:
	.string "I lost while I was lounging!$"

Route105_Text_ImaniPostBattle:
	.string "One Day of Peace.$"

Route105_Text_AndresIntro:
	.string "I'm convinced that the sea keeps\n"
	.string "Sinful Spoils from us.$"

Route105_Text_AndresDefeated:
	.string "Yes…\n"
	.string "I am no good at battling…$"

Route105_Text_AndresPostBattle:
	.string "I'm sure there are many secrets to be\n"
	.string "discovered in my wallet.\p"
	.string "I mean to find them all!$"

Route105_Text_AndresRegister:
	.string "Huh? I'm so weak, but you're willing\n"
	.string "to register me in your Pokénav?$"

Route105_Text_AndresRematchIntro:
	.string "I've told you that I'm weak…\n"
	.string "Are you sure you want to do this?$"

Route105_Text_AndresRematchDefeated:
	.string "Yes…\n"
	.string "I didn't think I could win.$"

Route105_Text_AndresRematchPostBattle:
	.string "I may be weak at battling, but my\n"
	.string "drive to explore can't be bested.\p"
	.string "I will travel the seas all around\n"
	.string "the world!$"

Route105_Text_JosueIntro:
	.string "I'm exhausted from swimming.\n"
	.string "I'm just not used to it.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_JosueDefeated:
	.string "I lost because I battled at sea.$"

Route105_Text_JosuePostBattle:
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route106_Text_ElliotIntro:
	.string "Which do you prefer, catfishing on\n"
	.string "a video or a stream?$"

Route106_Text_ElliotDefeated:
	.string "Like in deep-sea catfishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_ElliotRegister:
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro:
	.string "I caught a bunch of Pokémon fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated:
	.string "I lost again spectacularly!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Win or lose, Pokémon are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro:
	.string "What if my Rod hooks a big one while\n"
	.string "I'm in the washroom?\p"
	.string "Funny shit ensues.$"

Route106_Text_NedDefeated:
	.string "I lost because I'm trying to not go\n"
	.string "to the washroom…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! I've got this feeling I'll hook\n"
	.string "a big one!$"

Route106_Text_DouglasIntro:
	.string "Hahahah!$"

Route106_Text_DouglasDefeated:
	.string "Hahahah!$"

Route106_Text_DouglasPostBattle:
	.string "Hahahah!$"

Route106_Text_KylaIntro:
	.string "The sea is my backyard.\n"
	.string "Trespassing!$"

Route106_Text_KylaDefeated:
	.string "Did you take it easy on me by any\n"
	.string "chance?$"

Route106_Text_KylaPostBattle:
	.string "Drifting along with the waves…\n"
	.string "I love it! Why don't you give it a try?$"

Route107_Text_DarrinIntro:
	.string "Yawn…\p"
	.string "I must have drifted off to sleep while\n"
	.string "watching a Synchron turn.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, I lost…\n"
	.string "I'll take a Veiler, I think…$"

Route107_Text_DarrinPostBattle:
	.string "Floating and being rocked by\n"
	.string "the combos--it's like sleeping in\l"
	.string "Round 6 at X-2.$"

Route107_Text_TonyIntro:
	.string "The sea is like my backyard.\n"
	.string "Just need my grill!$"

Route107_Text_TonyDefeated:
	.string "I lost on my home field…\n"
	.string "I'm in shock!$"

Route107_Text_TonyPostBattle:
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "And a stomach full of steak.$"

Route107_Text_TonyRegister:
	.string "You've shocked me to the bone!\n"
	.string "Well, so you won't forget me…$"

Route107_Text_TonyRematchIntro:
	.string "Swimming in the big, wide sea,\n"
	.string "my Pokémon has grown stronger!$"

Route107_Text_TonyRematchDefeated:
	.string "What a shock!\p"
	.string "My Pokémon has gotten stronger, but\n"
	.string "I stayed weak as a TRAINER!$"

Route107_Text_TonyRematchPostBattle:
	.string "What you learn in battle makes you\n"
	.string "a stronger TRAINER.\l"
	.string "The waves taught me that.$"

Route107_Text_DeniseIntro:
	.string "Do you know a little town called\n"
	.string "Dewford?$"

Route107_Text_DeniseDefeated:
	.string "I hate Dewford!$"

Route107_Text_DenisePostBattle:
	.string "A cringe saying is getting really\n"
	.string "trendy at Dewford Hall.$"

Route107_Text_BethIntro:
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_BethDefeated:
	.string "I wasn't good enough for you.$"

Route107_Text_BethPostBattle:
	.string "Well, time to play some more\n"
	.string "Sinister Serpent control.$"

Route107_Text_LisaIntro:
	.string "Lisa: We challenge you as a sister\n"
	.string "and brother!$"

Route107_Text_LisaDefeated:
	.string "Lisa: We lost as sister and\n"
	.string "brother!$"

Route107_Text_LisaPostBattle:
	.string "Lisa: I'm teaching this little\n"
	.string "weasel how to swim.$"

Route107_Text_LisaNotEnoughPokemon:
	.string "Lisa: If you want to battle with us,\n"
	.string "bring more than one Pokémon.$"

Route107_Text_RayIntro:
	.string "Ray: We always battle Pokémon,\n"
	.string "me and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_RayDefeated:
	.string "Ray: We lost 1-on-2!$"

Route107_Text_RayPostBattle:
	.string "Ray: My sister gave me my Pokémon.\n"
	.string "I raised it, and now it's my important\l"
	.string "partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "Ray: If you want to battle us,\n"
	.string "go bring some more Pokémon!$"

Route107_Text_CamronIntro:
	.string "I'm in the middle of the RC-1 test,\n"
	.string "but I'm nowhere near tired!$"

Route107_Text_CamronDefeated:
	.string "That exhausted me…$"

Route107_Text_CamronPostBattle:
	.string "I still have PC-1 and DC-1\n"
	.string "to do after this.\p"
	.string "Am I okay?$"

Route108_Text_JeromeIntro:
	.string "Super Nimble Mega Hamster!$"

Route108_Text_JeromeDefeated:
	.string "Super Nimble Mega Hamster!$"

Route108_Text_JeromePostBattle:
	.string "Super Nimble Mega Hamster!$"

Route108_Text_MatthewIntro:
	.string "Ahoy, there! Are you going out to\n"
	.string "the Titenic, too?$"

Route108_Text_MatthewDefeated:
	.string "Titanic?\n"
	.string "No, no, I said Titenic.$"

Route108_Text_MatthewPostBattle:
	.string "Peak bootleg game.$"

Route108_Text_TaraIntro:
	.string "My liar of a boyfriend told me that\n"
	.string "I look great in a bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, damn it!$"

Route108_Text_TaraPostBattle:
	.string "Even if it's a lie, I love being told\n"
	.string "I look great…\l"
	.string "We girls are so complex…$"

Route108_Text_MissyIntro:
	.string "I love the sea!\n"
	.string "I forget all my worries when I swim!$"

Route108_Text_MissyDefeated:
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_MissyPostBattle:
	.string "Work off your stress by swimming!\n"
	.string "It's so healthy!$"

Route108_Text_CoryIntro:
	.string "I love Yu-Gi-Oh Duel Monsters.\n"
	.string "I, uh… the others exist.$"

Route108_Text_CoryDefeated:
	.string "No! My field power bonus!$"

Route108_Text_CoryPostBattle:
	.string "Gonna toss those Exodia pieces\n"
	.string "into the water.$"

Route108_Text_CoryRegister:
	.string "I love tough TRAINERS, too!\n"
	.string "Register me in your Pokénav!$"

Route108_Text_CoryRematchIntro:
	.string "Win or lose, I love battling at sea!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah! I lost again!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "If you're faced with a challenge,\n"
	.string "try shouting at the sea!$"

Route108_Text_CarolinaIntro:
	.string "I take huge pride in my Pokémon.\n"
	.string "We'll show you one speedy battle!$"

Route108_Text_CarolinaDefeated:
	.string "That was fast.$"

Route108_Text_CarolinaPostBattle:
	.string "Since I'm at sea like this, I wouldn't\n"
	.string "mind putting on a pink, frilly swimsuit…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "I cut myself!$"

Route109_Text_DavidPostBattle:
	.string "Stepped on some coral…$"

Route109_Text_AliceIntro:
	.string "Are you properly protected against\n"
	.string "burns?$"

Route109_Text_AliceDefeated:
	.string "Ouch, ouch, ouch!$"

Route109_Text_AlicePostBattle:
	.string "That lit a fire under my ass!$"

Route109_Text_HueyIntro:
	.string "I've laid anchor in ports around\n"
	.string "the world, but Slateport's the best.$"

Route109_Text_HueyDefeated:
	.string "You're the best!$"

Route109_Text_HueyPostBattle:
	.string "In the best port was the best\n"
	.string "Trainer…$"

Route109_Text_EdmondIntro:
	.string "I drank a whole bottle of ipecac.\n"
	.string "Worst bet I've ever taken.$"

Route109_Text_EdmondDefeated:
	.string "Wow…\n"
	.string "Induced vomiting blows.$"

Route109_Text_EdmondPostBattle:
	.string "Not worth it…$"

Route109_Text_RickyIntro:
	.string "I'm thirsty… I could go for a SODA!!!\n"
	.string "at the Seashore House…$"

Route109_Text_RickyDefeated:
	.string "My SODA!!! money…$"

Route109_Text_RickyPostBattle:
	.string "My inner tube looks like a\n"
	.string "giant doughnut… I am starving.$"

Route109_Text_RickyRegister:
	.string "Will you have another match with me\n"
	.string "when I'm not all thirsty?$"

Route109_Text_RickyRematchIntro:
	.string "I'm hungry, but I've got enough pep in\n"
	.string "me for a battle!$"

Route109_Text_RickyRematchDefeated:
	.string "I lost…\n"
	.string "It's because I'm hungry…$"

Route109_Text_RickyRematchPostBattle:
	.string "When you eat on a beach, everything\n"
	.string "seems to taste a little better.$"

Route109_Text_LolaIntro:
	.string "Doesn't a beach umbrella look like\n"
	.string "a giant flower?$"

Route109_Text_LolaDefeated:
	.string "Should have used Rose Dragons!$"

Route109_Text_LolaPostBattle:
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_LolaRegister:
	.string "Me?\n"
	.string "I'm here every day!$"

Route109_Text_LolaRematchIntro:
	.string "I'm not losing to you again!\n"
	.string "That's why I have my inner tube!$"

Route109_Text_LolaRematchDefeated:
	.string "Mommy!$"

Route109_Text_LolaRematchPostBattle:
	.string "If I have an inner tube, me and my\n"
	.string "Pokémon's cuteness goes way up!$"

Route109_Text_AustinaIntro:
	.string "I can't swim without my inner tube,\n"
	.string "but I won't lose at Pokémon!$"

Route109_Text_AustinaDefeated:
	.string "Did I lose because I have an inner\n"
	.string "tube?$"

Route109_Text_AustinaPostBattle:
	.string "My inner tube is a fashion item.\n"
	.string "I can't be seen without it.$"

Route109_Text_GwenIntro:
	.string "Hi, Big Piece Golem.\n"
	.string "Will you battle with me?$"

Route109_Text_GwenDefeated:
	.string "Oh, you're summoned without Tributes.$"

Route109_Text_GwenPostBattle:
	.string "How did you get to be so strong?$"

Route109_Text_CarterIntro:
	.string "Wahahah! This dude's going to catch\n"
	.string "himself an L!$"

Route109_Text_CarterDefeated:
	.string "Like I said!$"

Route109_Text_CarterPostBattle:
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_PaulIntro:
	.string "Paul: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't disturb our\n"
	.string "precious time together.$"

Route109_Text_PaulDefeated:
	.string "Paul: Well, I give up.$"

Route109_Text_PaulPostBattle:
	.string "Paul: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "Paul: We're totally, deeply in love.\n"
	.string "And you're a loner.$"

Route109_Text_MelIntro:
	.string "Mel: We're, like, totally in love.\n"
	.string "Our romance is heating up all of Hoenn!$"

Route109_Text_MelDefeated:
	.string "Mel: We lost, and I'm going\n"
	.string "to blame climate change!$"

Route109_Text_MelPostBattle:
	.string "Mel: Um, Paul, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_MelNotEnoughPokemon:
	.string "Mel: We're, like, deeply and truly in love.\n"
	.string "And you have no one.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! See?\n"
	.string "My inner tube's round!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "My win record is round!$"

Route109_Text_ChandlerPostBattle:
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_HaileyIntro:
	.string "I can't fish, so I'm pretending\n"
	.string "to play Frogs.$"

Route109_Text_HaileyDefeated:
	.string "I thought so!\n"
	.string "I didn't think we could win.$"

Route109_Text_HaileyPostBattle:
	.string "Frog FTK is pretty old.$"

Route109_Text_ElijahIntro:
	.string "For a guy as macho as me, this kind\n"
	.string "of Pokémon is the perfect match!$"

Route109_Text_ElijahDefeated:
	.string "Not macho, just bozo…$"

Route109_Text_ElijahPostBattle:
	.string "For a guy as macho as me, a port\n"
	.string "is the perfect setting!\p"
	.string "I guess I'll head for Slateport.$"

Route110_Text_JacobIntro:
	.string "Whoa! Watch it!\p"
	.string "I guess you're not used to card games\n"
	.string "on motorcycles!$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_JacobPostBattle:
	.string "I'm just like Yusei, for real.$"

Route110_Text_AnthonyIntro:
	.string "So long, suckers!$"

Route110_Text_AnthonyDefeated:
	.string "I rev up my motorcycle and\n"
	.string "create a huge cloud of smoke.$"

Route110_Text_AnthonyPostBattle:
	.string "When the cloud dissipates I'm lying\n"
	.string "completely dead on the pavement.$"

Route110_Text_BenjaminIntro:
	.string "Tonight on Bottom Gear…\p"
	.string "I lose a Pokémon battle.\p"
	.string "Jacob crashes his bicycle while\n"
	.string "dueling an Earthbound Immortal.\p"
	.string "And Anthony is dead on the pavement.$"

Route110_Text_BenjaminDefeated:
	.string "Oh no… anyway.$"

Route110_Text_BenjaminPostBattle:
	.string "Let's not get bogged down with\n"
	.string "who lost a battle.$"

Route110_Text_BenjaminRegister:
	.string "I'll keep chugging on without stressing.\n"
	.string "Give me a shout if you're up to it.$"

Route110_Text_BenjaminRematchIntro:
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_BenjaminRematchDefeated:
	.string "I didn't panic, but I still lost…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_AbigailIntro:
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to do three events:\n"
	.string "judge calls, deck checks, match slips.$"

Route110_Text_AbigailDefeated:
	.string "Pokémon battles are hard, too!$"

Route110_Text_AbigailPostBattle:
	.string "I'm exhausted, so I need a break.\n"
	.string "Lunch break starts next round.$"

Route110_Text_AbigailRegister:
	.string "You know, I like you!\n"
	.string "Let's have a rematch on CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "How could you be so strong?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro:
	.string "I've been riding without stopping.\n"
	.string "My thighs are like rocks!$"

Route110_Text_JasmineDefeated:
	.string "Lactic acid…$"

Route110_Text_JasminePostBattle:
	.string "I'll be immobilized tomorrow.$"

Route110_Text_EdwardIntro:
	.string "I have foreseen your next YCS run!\n"
	.string "You cannot possibly lose!$"

Route110_Text_EdwardDefeated:
	.string "No, wait! You'll go X-3 drop!$"

Route110_Text_EdwardPostBattle:
	.string "I see your future…\p"
	.string "Hmm…\n"
	.string "I see no top cut deck profiles…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "I'll dazzle you with my Starlights!$"

Route110_Text_JaclynDefeated:
	.string "I expensively lost!$"

Route110_Text_JaclynPostBattle:
	.string "You managed to win only because it was\n"
	.string "a bad Starlight! Yes, terrible!$"

Route110_Text_EdwinIntro:
	.string "Could I see your trade binder?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinDefeated:
	.string "Wow, you have nothing good.$"

Route110_Text_EdwinPostBattle:
	.string "When I see someone I haven't scammed,\n"
	.string "my passion as a rat is ignited!$"

Route110_Text_EdwinRegister:
	.string "I like collecting MATCH CALL\n"
	.string "registrations, too…$"

Route110_Text_EdwinRematchIntro:
	.string "Hi, have you caught any new Pokémon?\p"
	.string "Could I see your Pokémon?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinRematchDefeated:
	.string "Your Pokémon…\n"
	.string "I envy you.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, I long to make all rare Pokémon\n"
	.string "mine!$"

Route110_Text_DaleIntro:
	.string "Hey!\n"
	.string "Don't sneak up behind me like that!$"

Route110_Text_DaleDefeated:
	.string "I lost because I was\n"
	.string "sneak attacked!$"

Route110_Text_DalePostBattle:
	.string "Fishing is all about concentration.\n"
	.string "You have to focus on the floater.\l"
	.string "No, not mine.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! I would go anywhere to show\n"
	.string "off my delightful Pokémon.$"

Route110_Text_IsabelDefeated:
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelPostBattle:
	.string "Rather than battling, perhaps I should\n"
	.string "show off my vlogging skills.$"

Route110_Text_IsabelRegister:
	.string "That wasn't close to what I could\n"
	.string "do to show off my Pokémon.\p"
	.string "I'll have you as my captive audience\n"
	.string "as often as possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my Pokémon as often as you like!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelRematchPostBattle:
	.string "I don't think that I could ever stop\n"
	.string "from showing off my Pokémon.\p"
	.string "But I like to battle, too!$"

Route110_Text_TimmyIntro:
	.string "I found some cool Pokémon in the grass\n"
	.string "around here!$"

Route110_Text_TimmyDefeated:
	.string "Being cool isn't enough to win…$"

Route110_Text_TimmyPostBattle:
	.string "It's hard to battle with Pokémon you\n"
	.string "just caught.$"

Route110_Text_AlyssaIntro:
	.string "I fell off Cycling Road…\p"
	.string "Don't ask how!$"

Route110_Text_AlyssaDefeated:
	.string "Okay, fine, I ran into Trap Hole!$"

Route110_Text_AlyssaPostBattle:
	.string "Falling… Losing…\n"
	.string "This is so humiliating for me!$"

Route110_Text_JosephIntro:
	.string "Okay! Full-throttle time! If you can't\n"
	.string "groove, you get left behind!$"

Route110_Text_JosephDefeated:
	.string "You got into the groove all right…$"

Route110_Text_JosephPostBattle:
	.string "I need to practice F.A. combos.$"

Route110_Text_KalebIntro:
	.string "When cute Pokémon help each other…\n"
	.string "You won't see a more adorable sight!$"

Route110_Text_KalebDefeated:
	.string "Have you no compassion or pity?$"

Route110_Text_KalebPostBattle:
	.string "Pikachu knockoffs are the best.$"

Route111_Text_DrewIntro:
	.string "Oh, hey! Those Go-Goggles suit you.\n"
	.string "But I think they look better on me.\p"
	.string "I'll steal yours!$"

Route111_Text_DrewDefeat:
	.string "Well, that was miserable.$"

Route111_Text_DrewPostBattle:
	.string "The Go-Goggles make it possible to\n"
	.string "get through sandstorms.\l"
	.string "More to eat.$"

Route111_Text_HeidiIntro:
	.string "My regionals is on lunch break.\n"
	.string "Want to practice?$"

Route111_Text_HeidiDefeat:
	.string "Oof! You're good!$"

Route111_Text_HeidiPostBattle:
	.string "I hear you need Go-Goggles to\n"
	.string "brave the sands.$"

Route111_Text_BeauIntro:
	.string "Wearing these Go-Goggles makes me\n"
	.string "feel like a biker.\l"
	.string "Right now, nobody can beat me!$"

Route111_Text_BeauDefeat:
	.string "I'm not as cool as Wes…$"

Route111_Text_BeauPostBattle:
	.string "I'm going to be a real hero one day.\n"
	.string "I'm going to work harder to make me\l"
	.string "and my Pokémon stronger.$"

Route111_Text_BeckyIntro:
	.string "I heard there are fossils to be found\n"
	.string "in the desert. Where could they be?$"

Route111_Text_BeckyDefeat:
	.string "I came up short…$"

Route111_Text_BeckyPostBattle:
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_DustyIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient UN UN UN!$"

Route111_Text_DustyDefeat:
	.string "While I have searched for UN UN UN,\n"
	.string "I've not searched for strong Pokémon.$"

Route111_Text_DustyPostBattle:
	.string "For thirty years I have searched for\n"
	.string "ancient UN UN UN!\p"
	.string "No, wait, was that forty years?\n"
	.string "How old am I?$"

Route111_Text_DustyRegister:
	.string "I haven't been searching for any\n"
	.string "tough Pokémon.\p"
	.string "But, for some reason, I sure do like\n"
	.string "PokénavS.$"

Route111_Text_DustyRematchIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat:
	.string "I've found no ruins, nor have I found\n"
	.string "any strong Pokémon…$"

Route111_Text_DustyPostRematch:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years\n"
	.string "I've searched?\p"
	.string "Hmm… It could even be fifty…\n"
	.string "How long have I been at this?$"

Route111_Text_TravisIntro:
	.string "I'm full of pepper!\n"
	.string "I like spicy food!$"

Route111_Text_TravisDefeat:
	.string "Need some water…$"

Route111_Text_TravisPostBattle:
	.string "When I see a recipe with a lot of\n"
	.string "pepper, I can't help cooking.$"

Route111_Text_IreneIntro:
	.string "I don't know where you're going,\n"
	.string "but would you like to battle?$"

Route111_Text_IreneDefeat:
	.string "Seems like you're on the way up!$"

Route111_Text_IrenePostBattle:
	.string "I'm thinking that I should go to\n"
	.string "Mt. Chimney, but the view around\l"
	.string "here is very nice, too.$"

Route111_Text_DaisukeIntro:
	.string "To train myself, I challenge all\n"
	.string "whom I meet!$"

Route111_Text_DaisukeDefeat:
	.string "To humble myself, I lose to all\n"
	.string "that I meet!$"

Route111_Text_DaisukePostBattle:
	.string "To feed myself, I season all\n"
	.string "my meat!$"

Route111_Text_WiltonIntro:
	.string "Show me how much you've reached\n"
	.string "X-0 at Round 4.$"

Route111_Text_WiltonDefeat:
	.string "I see, you've won the coinflip.$"

Route111_Text_WiltonPostBattle:
	.string "What's important is to never lose.$"

Route111_Text_WiltonRegister:
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_WiltonRematchIntro:
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:
	.string "Since you're that strong, you should\n"
	.string "aim for the Pokémon LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "Oh, your Pokémon look like serious\n"
	.string "actors.\l"
	.string "I have to ask you for an autograph.$"

Route111_Text_BrookeDefeat:
	.string "They didn't just look strong,\n"
	.string "they are strong!$"

Route111_Text_BrookePostBattle:
	.string "I thought I was raising my Pokémon\n"
	.string "diligently, but you're nuts.$"

Route111_Text_BrookeRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "You can make Pokémon stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your Pokémon\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat:
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should have stopped my\n"
	.string "Pokémon from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_CeliaIntro:
	.string "I'm having a picnic in the desert.\n"
	.string "Where else would a sandwich be eaten?$"

Route111_Text_CeliaDefeat:
	.string "Ohhh! My sandstorm sandwich!$"

Route111_Text_CeliaPostBattle:
	.string "Rock types are less vulnerable to\n"
	.string "special attacks in Sandstorm.$"

Route111_Text_BryanIntro:
	.string "How tough are you?\n"
	.string "We shall expose that secret!$"

Route111_Text_BryanDefeat:
	.string "I've been exposed!$"

Route111_Text_BryanPostBattle:
	.string "This desert hoards mysteries in\n"
	.string "its shifting sands!$"

Route111_Text_BrandenIntro:
	.string "I'll give you some of my sandwich\n"
	.string "if you'll lose.$"

Route111_Text_BrandenDefeat:
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_BrandenPostBattle:
	.string "My Sandshrew loves eating sand.$"

Route111_Text_TyronIntro:
	.string "This is my favorite kind of Pokémon!$"

Route111_Text_TyronDefeat:
	.string "Wait!\n"
	.string "Did you get a good look at my Pokémon?$"

Route111_Text_TyronPostBattle:
	.string "When having a battle, I get a kick out\n"
	.string "of showing off my Pokémon.\p"
	.string "I bet everyone feels that way when\n"
	.string "they enter a battle!$"

Route111_Text_CelinaIntro:
	.string "Show me how to put a little spice\n"
	.string "into my deckbuilding.$"

Route111_Text_CelinaDefeat:
	.string "Oh… My…\n"
	.string "That was too much spice.$"

Route111_Text_CelinaPostBattle:
	.string "Maybe I should play Nouvellez.$"

Route111_Text_HaydenIntro:
	.string "When you're as famished as I am,\n"
	.string "there is no room for pity!$"

Route111_Text_HaydenDefeat:
	.string "Groan…$"

Route111_Text_HaydenPostBattle:
	.string "My stomach is grumbling!\n"
	.string "Maybe I can grill some lettuce…$"

Route111_Text_BiancaIntro:
	.string "Did you come from Mauville?\n"
	.string "Then you better call Saul!$"

Route111_Text_BiancaDefeat:
	.string "That's a hard loss!$"

Route111_Text_BiancaPostBattle:
	.string "This road here…\n"
	.string "You have quite a ways to travel.$"

Route112_Text_BriceIntro:
	.string "Hee hee hee ha!$"

Route112_Text_BriceDefeat:
	.string "Hee hee hee ha!$"

Route112_Text_BricePostBattle:
	.string "Hee hee hee ha!$"

Route112_Text_TrentIntro:
	.string "My legs are solid from pounding up\n"
	.string "and down the mountains.\p"
	.string "They're not going to buckle easily,\n"
	.string "friend!$"

Route112_Text_TrentDefeat:
	.string "Ouch! My legs cramped up!$"

Route112_Text_TrentPostBattle:
	.string "Try hiking, and I mean really\n"
	.string "pounding, while smoking that pack.\p"
	.string "RIPBOZO$"

Route112_Text_TrentRegister:
	.string "Ow, my legs have cramped up.\n"
	.string "Can you grab me some bandages from\l"
	.string "my backpack?\p"
	.string "No, that's my Pokénav!\n"
	.string "Oh, fine, I'll register you.$"

Route112_Text_TrentRematchIntro:
	.string "I've been keeping fit by hiking.\n"
	.string "Power, I have in spades!$"

Route112_Text_TrentRematchDefeat:
	.string "I got trumped in power?$"

Route112_Text_TrentRematchPostBattle:
	.string "I hear there are some seriously tough\n"
	.string "TRAINERS on top of MT. CHIMNEY.\p"
	.string "I intend to get up there and give them\n"
	.string "a challenge!$"

Route112_Text_LarryIntro:
	.string "I won't cry if I cut onions.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "I'm not crying because I hate onions!\n"
	.string "Snivel…$"

Route112_Text_CarolIntro:
	.string "Never gonna give you up!$"

Route112_Text_CarolDefeat:
	.string "Never gonna let you down!$"

Route112_Text_CarolPostBattle:
	.string "I can't run, so the next part's out.$"

Route112_Text_BryantIntro:
	.string "Fuck you for bringing up\n"
	.string "Serpentine Princess.$"

Route112_Text_BryantDefeat:
	.string "Nooo don't shuffle me!$"

Route112_Text_BryantPostBattle:
	.string "Now I can't summon a Level 3\n"
	.string "from the Deck.$"

Route112_Text_ShaylaIntro:
	.string "They speak English in What?$"

Route112_Text_ShaylaDefeat:
	.string "English, motherfucker,\n"
	.string "do you speak it!?$"

Route112_Text_ShaylaPostBattle:
	.string "Divine intervention, motherfucker.$"

Route113_Text_JaylenIntro:
	.string "Can you guess why it's so cool\n"
	.string "around here?$"

Route113_Text_JaylenDefeat:
	.string "Brionac prio effect!$"

Route113_Text_JaylenPostBattle:
	.string "Ice Barriers block sensible card design,\n"
	.string "so it doesn't get cooked with.\p"
	.string "That's good for me--I can't stand heat!$"

Route113_Text_DillonIntro:
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive.$"

Route113_Text_DillonDefeat:
	.string "Volcussy.$"

Route113_Text_DillonPostBattle:
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that joke was ash…$"

Route113_Text_MadelineIntro:
	.string "I use this parasol to ward off this\n"
	.string "filthy, yucky Ash Blossom from\l"
	.string "my dear Future Fusion.$"

Route113_Text_MadelineDefeat:
	.string "I couldn't dump my Machines…$"

Route113_Text_MadelinePostBattle:
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_MadelineRegister:
	.string "Here, slide under my parasol.\n"
	.string "Let me register you in my Pokénav.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch:
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_LaoIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostBattle:
	.string "I must refine the art of Crossout\n"
	.string "declare Ash. I bid thee farewell.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of Pokénav registration!$"

Route113_Text_LaoRematchIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_LungDefeat:
	.string "I'll use my ninjutsu on you…\n"
	.string "“Ninjitsu Art Tool - Iron Digger”!\p"
	.string "…What?\n"
	.string "Two different spellings?$"

Route113_Text_LungPostBattle:
	.string "You know what's crummy about hiding?\n"
	.string "Bread.$"

Route113_Text_ToriIntro:
	.string "Tori: Both of us, we collect ashes.\n"
	.string "We collect rats, too.$"

Route113_Text_ToriDefeat:
	.string "Tori: We lost… It's boring, so I'm going\n"
	.string "to get some more rats.$"

Route113_Text_ToriPostBattle:
	.string "Tori: How much ash do we have?\n"
	.string "Enough for a White Flute, I hope.$"

Route113_Text_ToriNotEnoughMons:
	.string "Tori: We want to battle 2-on-2.\n"
	.string "If we didn't, we would scrub out!$"

Route113_Text_TiaIntro:
	.string "Tia: Both of us, we collect ashes.\n"
	.string "We collect rats, too.$"

Route113_Text_TiaDefeat:
	.string "Tia: We couldn't win… It's boring,\n"
	.string "so I'm getting some more rats.$"

Route113_Text_TiaPostBattle:
	.string "Tia: We have a lot of ashes!\n"
	.string "I think enough for a White Flute!$"

Route113_Text_TiaNotEnoughMons:
	.string "Tia: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "Pfft, with these wings I can\n"
	.string "play Blackwings!$"

Route113_Text_CobyDefeat:
	.string "I missed Damage Step?$"

Route113_Text_CobyPostBattle:
	.string "What is a way to beat Armades…$"

Route113_Text_SophieIntro:
	.string "The warmth here is making me drowsy.\n"
	.string "Battle with me or I'll play Nemleria.$"

Route113_Text_SophieDefeat:
	.string "A mimir…$"

Route113_Text_SophiePostBattle:
	.string "I'm just going to sleep right here!$"

Route113_Text_LawrenceIntro:
	.string "Were you maybe in the middle\n"
	.string "of gathering volcanic ashes?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "We got beaten cleanly.$"

Route113_Text_LawrencePostBattle:
	.string "You can trade all that Ash for Flutes,\n"
	.string "if you have a Soot Sack.$"

Route113_Text_WyattIntro:
	.string "Y-you want to battle with me?\n"
	.string "Even though I just caught my Pokémon?$"

Route113_Text_WyattDefeat:
	.string "Y-you're all happy to win?\n"
	.string "Even though it's only me?$"

Route113_Text_WyattPostBattle:
	.string "Oh, so now you want to say a word to\n"
	.string "the loser?\p"
	.string "Well, get bent!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "It doesn't echo here…$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone called “Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_LucasDefeat:
	.string "The mountains are unforgiving…$"

Route114_Text_LucasPostBattle:
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_ShaneIntro:
	.string "Camping's fun! You can fish!\p"
	.string "You know what that means!\n"
	.string "Fish!$"

Route114_Text_ShaneDefeat:
	.string "I don't have any fish!$"

Route114_Text_ShanePostBattle:
	.string "I think it's great that I can go\n"
	.string "fishing with my Pokémon.$"

Route114_Text_NancyIntro:
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_NancyDefeat:
	.string "I meant Best of 3!$"

Route114_Text_NancyPostBattle:
	.string "I just had a tasty meal.\n"
	.string "Now for Round 5…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Want to battle against my Pokémon?$"

Route114_Text_SteveDefeat:
	.string "M-My Pokémon…$"

Route114_Text_StevePostBattle:
	.string "You know who else wants to battle\n"
	.string "against my Pokémon?$"

Route114_Text_SteveRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, battle my Pokémon…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky getting to see your\n"
	.string "Pokémon…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I see Pokémon battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro:
	.string "If you're lighting a campfire,\n"
	.string "make sure you have water handy.$"

Route114_Text_BernieDefeat:
	.string "Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of Poplar eff summon Poplar add Ash.$"

Route114_Text_BernieRegister:
	.string "You set my spirit on fire.\n"
	.string "Let's register each other!$"

Route114_Text_BernieRematchIntro:
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_BerniePostRematch:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your Pokémon!$"

Route114_Text_ClaudeDefeat:
	.string "If we were fishing, I would've won…$"

Route114_Text_ClaudePostBattle:
	.string "I've got fish to catch.$"

Route114_Text_NolanIntro:
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_NolanDefeat:
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_NolanPostBattle:
	.string "I'm really gonna do it.$"

Route114_Text_TyraIntro:
	.string "Tyra: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about Madolche.$"

Route114_Text_TyraDefeat:
	.string "Tyra: What an amazing shuffle!$"

Route114_Text_TyraPostBattle:
	.string "Tyra: I was teaching my junior Ivy\n"
	.string "about Hootcake combos.$"

Route114_Text_TyraNotEnoughMons:
	.string "Tyra: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "Anjelly isn't enough!$"

Route114_Text_IvyIntro:
	.string "Ivy: Who taught you about Madolches?$"

Route114_Text_IvyDefeat:
	.string "Ivy: What an amazing French accent!$"

Route114_Text_IvyPostBattle:
	.string "Ivy: I started trying Tiaramisu eff\n"
	.string "because Tyra, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons:
	.string "Ivy: Do you only have one pastry?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_KaiIntro:
	.string "I landed a big one!\n"
	.string "A huge one, I tell you!$"

Route114_Text_KaiDefeat:
	.string "What was that about?\n"
	.string "Did mine lose in size?$"

Route114_Text_KaiPostBattle:
	.string "Don't read into that.$"

Route114_Text_CharlotteIntro:
	.string "Me!\n"
	.string "I'm not just a Synchro player!$"

Route114_Text_CharlotteDefeat:
	.string "That wasn't hyperdrive in the least!$"

Route114_Text_CharlottePostBattle:
	.string "I don't want a Pokémon that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that are Tuners!$"

Route114_Text_AngelinaIntro:
	.string "Have you made your Pokémon evolve\n"
	.string "very much?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, I see.\n"
	.string "Wooooow.$"

Route114_Text_AngelinaPostBattle:
	.string "Some Pokémon change so much when\n"
	.string "they evolve, it's a banger!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "You seem rather capable…\l"
	.string "Let me keep you company!$"

Route115_Text_TimothyDefeat:
	.string "You're some lethal company!$"

Route115_Text_TimothyPostBattle:
	.string "I must make for bad company.$"

Route115_Text_TimothyRegister:
	.string "Hmm… A loss this thorough has been\n"
	.string "a distant memory.\p"
	.string "If you would allow it, I wish for\n"
	.string "another opportunity to do battle.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch:
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:
	.string "You!\p"
	.string "I can feel your aura!\p"
	.string "I demand a battle!$"

Route115_Text_KoichiDefeat:
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:
	.string "My Riolu crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_NobIntro:
	.string "My strongest skill is busting bricked\n"
	.string "hands with my forehead!$"

Route115_Text_NobDefeat:
	.string "My head is busted!$"

Route115_Text_NobPostBattle:
	.string "Now I'll have a dent in my head!$"

Route115_Text_NobRegister:
	.string "You impress me! Give me a rematch\n"
	.string "after I redo my training!$"

Route115_Text_NobRematchIntro:
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_NobPostRematch:
	.string "My Pokémon will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_CyndyIntro:
	.string "This beach is my secret training spot!\n"
	.string "Don't interrupt my Plunder combos!$"

Route115_Text_CyndyDefeat:
	.string "I haven't Moerk'd enough!$"

Route115_Text_CyndyPostBattle:
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_CyndyRegister:
	.string "Okay, fine, you're free to come here.\n"
	.string "In return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "I can battle but my Pokémon…$"

Route115_Text_CyndyPostRematch:
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love Pokémon.$"

Route115_Text_HectorIntro:
	.string "I have a Chaos Neos misprint!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorDefeat:
	.string "You…\n"
	.string "You want my Chaos Neos, don't you?$"

Route115_Text_HectorPostBattle:
	.string "I have this rare Chaos Neos.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_KyraIntro:
	.string "I'll battle while I'm running!\n"
	.string "Try to keep up with me!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp…$"

Route115_Text_KyraPostBattle:
	.string "That was not a good idea…$"

Route115_Text_JaidenIntro:
	.string "Take that!\n"
	.string "Ultra Rare ninja attack!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_JaidenPostBattle:
	.string "But my cards were Ultra Rare,\n"
	.string "weren't they?$"

Route115_Text_HeleneIntro:
	.string "My Pokémon have War Rock-level\n"
	.string "strength!$"

Route115_Text_HeleneDefeat:
	.string "This is too humiliating!$"

Route115_Text_HelenePostBattle:
	.string "I rarely meet anyone who's better\n"
	.string "than me…\p"
	.string "I get it now! You bought out\n"
	.string "War Rock Mountain, didn't you?$"

Route115_Text_AlixIntro:
	.string "Our eyes met!\n"
	.string "There's no getting away now!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "Not bad!$"

Route115_Text_AlixPostBattle:
	.string "Oh, well.\n"
	.string "I think I will fast travel home.$"

Route115_Text_MarleneIntro:
	.string "You've disturbed my meditation…\n"
	.string "You'll be atomized for it.$"

Route115_Text_MarleneDefeat:
	.string "You've broken my concentration!$"

Route115_Text_MarlenePostBattle:
	.string "I was meditating with my Pokémon.\n"
	.string "But you're a gremlin…$"

Route116_Text_ClarkIntro:
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go Larvitar mode.$"

Route116_Text_ClarkDefeat:
	.string "Delicious mountain.$"

Route116_Text_ClarkPostBattle:
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a Hiker, mountains are food!$"

Route116_Text_JoeyIntro:
	.string "My Mekk-Knight Avrams rule!\n"
	.string "Check THIS out!$"

Route116_Text_JoeyDefeat:
	.string "Ouch! A scrape!\n"
	.string "I have to use a Mekk-Knight bandage!$"

Route116_Text_JoeyPostBattle:
	.string "Mekk-Knights are signs of toughness!\n"
	.string "I've got another search!$"

Route116_Text_JoseIntro:
	.string "My Bug Pokémon are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:
	.string "My Bug Pokémon aren't tough!$"

Route116_Text_JosePostBattle:
	.string "Standard Verdant Sanctuary moment.$"

Route116_Text_JaniceIntro:
	.string "Let me teach you how strong my\n"
	.string "70 dollar playmat is!$"

Route116_Text_JaniceDefeat:
	.string "Your playmat is cooler…$"

Route116_Text_JanicePostBattle:
	.string "Playmats that possess cuteness and\n"
	.string "zones, that's ideal, I think.$"

Route116_Text_JerryIntro:
	.string "We learn all sorts of things at the\n"
	.string "Trainer's School.\p"
	.string "Like how to Synchro Summon!$"

Route116_Text_JerryDefeat:
	.string "I slacked off in school…\n"
	.string "That's why I can't count.$"

Route116_Text_JerryPostBattle:
	.string "I'll have to redo some courses at\n"
	.string "the math level.$"

Route116_Text_JerryRegister1:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a Pokénav can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRegister2:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a Pokénav can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRematchIntro:
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch:
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:
	.string "I study at school, and I study on\n"
	.string "the way home, too!$"

Route116_Text_KarenDefeat:
	.string "I lost? I'll have to study that.$"

Route116_Text_KarenPostBattle:
	.string "Awww, I guess I have to keep\n"
	.string "studying.$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Isn't that a Pokénav?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRegister2:
	.string "Oh, wow! Isn't that a Pokénav?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRematchIntro:
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch:
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"

Route116_Text_SarahIntro:
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at Melffy.$"

Route116_Text_SarahDefeat:
	.string "Oh, my goodness.\n"
	.string "This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "My life of luxury affords me all that\n"
	.string "I could possibly desire.\p"
	.string "However, when it comes to Melffy,\n"
	.string "my wealth has no meaning.$"

Route116_Text_DawsonIntro:
	.string "Ha! What can you hope to do against\n"
	.string "my deck comprised of entirely QCRs?$"

Route116_Text_DawsonDefeat:
	.string "But… I'm rich!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "I have less money now!$"

Route116_Text_DevanIntro:
	.string "We'll rock you hard!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "My Koa'ki Meirus!$"

Route116_Text_DevanPostBattle:
	.string "I should try different monster\n"
	.string "types, that's what I ought to do.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we shoot hoops?$"

Route116_Text_JohnsonDefeat:
	.string "Ah, we have no hoops up here.$"

Route116_Text_JohnsonPostBattle:
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route117_Text_IsaacIntro:
	.string "Listen, could I get you to battle\n"
	.string "the Pokémon I'm raising?$"

Route117_Text_IsaacDefeat:
	.string "That's what I'm talking about.$"

Route117_Text_IsaacPostBattle:
	.string "Pokémon isn't all about power.\p"
	.string "It would be wise to consider the\n"
	.string "capabilities of strategic moves.$"

Route117_Text_IsaacRegister:
	.string "I'm going to redouble my training.\n"
	.string "Would you come look in on us?$"

Route117_Text_IsaacRematchIntro:
	.string "The Pokémon I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_IsaacPostRematch:
	.string "Your Pokémon are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your Pokémon properly.$"

Route117_Text_LydiaDefeat:
	.string "Nicely done.$"

Route117_Text_LydiaPostBattle:
	.string "Apparently there's a blockage\n"
	.string "in Rusturf Tunnel.\p"
	.string "If someone used Rock Smash there,\n"
	.string "they'd clear the path.$"

Route117_Text_LydiaRegister:
	.string "I'm glad I met a superb TRAINER in you.\n"
	.string "I hope to see you again.$"

Route117_Text_LydiaRematchIntro:
	.string "Allow me to reevaluate if you have\n"
	.string "raised your Pokémon properly.$"

Route117_Text_LydiaRematchDefeat:
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch:
	.string "Pokémon seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's have a battle!$"

Route117_Text_DylanDefeat:
	.string "I ran out of energy!$"

Route117_Text_DylanPostBattle:
	.string "What's the triathlon route?\n"
	.string "I don't know…$"

Route117_Text_DylanRegister:
	.string "Pokémon have to be strong, too?\n"
	.string "I'd like you to train me!$"

Route117_Text_DylanRematchIntro:
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "I was tops in swimming and cycling,\n"
	.string "but I'm not quite that confident with\l"
	.string "Pokémon yet.$"

Route117_Text_MariaIntro:
	.string "I do my triathlon training with Pokémon,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:
	.string "My speed made me crash!$"

Route117_Text_MariaPostBattle:
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!$"

Route117_Text_MariaRegister:
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "Once a Bug Catcher!\n"
	.string "And now a Bug Maniac!\p"
	.string "Activate Lair Wire!$"

Route117_Text_DerekDefeat:
	.string "My ineptitude also remains\n"
	.string "unchanged…$"

Route117_Text_DerekPostBattle:
	.string "All I did was follow my heart, and now\n"
	.string "they call me a Beetrooper maniac…\l"
	.string "Still, I do be trooping.$"

Route117_Text_AnnaIntro:
	.string "Anna: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_AnnaDefeat:
	.string "Anna: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_AnnaPostBattle:
	.string "Anna: Your Pokémon have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "Anna: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route117_Text_AnnaNotEnoughMons:
	.string "Anna: If you want to battle us,\n"
	.string "bring two Pokémon with you.$"

Route117_Text_MegIntro:
	.string "Meg: I'm going to tag up with my super\n"
	.string "senior student partner and beat you!$"

Route117_Text_MegDefeat:
	.string "Meg: Oh, no!\n"
	.string "I'm sorry, Anna! I let you down…$"

Route117_Text_MegPostBattle:
	.string "Meg: I dragged Anna down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_MegNotEnoughMons:
	.string "Meg: Do you only have one Pokémon?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Your Pokémon have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: If you want to battle us,\n"
	.string "bring two Pokémon with you.$"

Route117_Text_MegRematchIntro:
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Too strong!$"

Route117_Text_MegPostRematch:
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Do you only have one Pokémon?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Isn't it nice? To battle while looking\n"
	.string "at Pretty Memory?$"

Route117_Text_MelinaDefeat:
	.string "Oh, that's an attach!$"

Route117_Text_MelinaPostBattle:
	.string "It feels wonderful to go for a jog\n"
	.string "while looking at Purrely.$"

Route117_Text_BrandiIntro:
	.string "Let me demonstrate the power\n"
	.string "hidden within emotional damage!$"

Route117_Text_BrandiDefeat:
	.string "Astonishing!$"

Route117_Text_BrandiPostBattle:
	.string "Emotional damage is complex.\n"
	.string "You should try incurring some.$"

Route117_Text_AishaIntro:
	.string "Concentrate on getting the win.\n"
	.string "That's how I battle!$"

Route117_Text_AishaDefeat:
	.string "I couldn't concentrate!$"

Route117_Text_AishaPostBattle:
	.string "Concentrate for 2.5x magic damage.$"

Route118_Text_RoseIntro:
	.string "The aroma of Rikka has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_RoseDefeat:
	.string "Oh, dear me.\n"
	.string "You popped Konkon.$"

Route118_Text_RosePostBattle:
	.string "Rikka, Sunavalon…\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky Mannadium…\n"
	.string "I'll pass.$"

Route118_Text_RoseRegister:
	.string "Sniff… That odor--it's a Pokénav!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "The power of aroma…\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch:
	.string "If you use a sweet aroma properly,\n"
	.string "Pokémon will be attracted by it.$"

Route118_Text_PerryIntro:
	.string "Floowandereeze decks that floodgate in\n"
	.string "the sky… They're the best!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "I bricked…$"

Route118_Text_PerryPostBattle:
	.string "You've got great skills.\n"
	.string "I'll have to draw Map better.$"

Route118_Text_ChesterIntro:
	.string "Take flight!\n"
	.string "My winged wackos!$"

Route118_Text_ChesterDefeat:
	.string "They did take flight…$"

Route118_Text_ChesterPostBattle:
	.string "If they'd get stronger, they'd be able\n"
	.string "to win…$"

Route118_Text_BarnyIntro:
	.string "I'm a Fisherman, but also a gamer.\n"
	.string "Catch me at Bass Pro Shops.$"

Route118_Text_BarnyDefeat:
	.string "I thought I was doing okay in my\n"
	.string "training…$"

Route118_Text_BarnyPostBattle:
	.string "I couldn't win by training Pokémon\n"
	.string "while I fished…\p"
	.string "I must redevelop my training style\n"
	.string "at the Bass Pro Shops Pyramid.$"

Route118_Text_WadeIntro:
	.string "For fishermen, rod skill is the key!$"

Route118_Text_WadeDefeat:
	.string "I dropped my rod!$"

Route118_Text_WadePostBattle:
	.string "Come to think of it, fishing is a battle\n"
	.string "between a Fisherman and his patience.$"

Route118_Text_DaltonIntro:
	.string "Let my melody rock your soul!$"

Route118_Text_DaltonDefeat:
	.string "Pizza mozzarella…$"

Route118_Text_DaltonPostBattle:
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "your wallet…$"

Route118_Text_DaltonRegister:
	.string "When I compose better melodies,\n"
	.string "you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "A melody from my Pokémon and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\n"
	.string "Pokémon 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Come in, Pokémon! Are you okay?\n"
	.string "Pokémon 1, 2, and 3?!$"

Route118_Text_DeandrePostBattle:
	.string "We've got a squad going here!$"

Route119_Text_BrentIntro:
	.string "We know your every move.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_BrentDefeat:
	.string "We will continue observing.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_BrentPostBattle:
	.string "You cannot run.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DonaldIntro:
	.string "We know your every move.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DonaldDefeat:
	.string "We will continue observing.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DonaldPostBattle:
	.string "You cannot run.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_TaylorIntro:
	.string "We know your every move.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_TaylorDefeat:
	.string "We will continue observing.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_TaylorPostBattle:
	.string "You cannot run.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DougIntro:
	.string "We know your every move.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DougDefeat:
	.string "We will continue observing.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_DougPostBattle:
	.string "You cannot run.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_GregIntro:
	.string "We know your every move.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_GregDefeat:
	.string "We will continue observing.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_GregPostBattle:
	.string "You cannot run.\n"
	.string "For we are the Mimic Circle.$"

Route119_Text_KentIntro:
	.string "These other guys freak me out.$"

Route119_Text_KentDefeat:
	.string "Why do they keep following you?$"

Route119_Text_KentPostBattle:
	.string "Me? I'm trying to blend in.$"

Route119_Text_JacksonIntro:
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "Pokémon Rangers, that's who!$"

Route119_Text_JacksonDefeat:
	.string "I didn't have enough Pokémon\n"
	.string "know-how…$"

Route119_Text_JacksonPostBattle:
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRegister:
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with Pokémon.$"

Route119_Text_JacksonRematchDefeat:
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:
	.string "Believe in your Pokémon.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure,\n"
	.string "you're traveling awfully light.$"

Route119_Text_CatherineDefeat:
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherinePostBattle:
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "Except toilet paper. You need that.$"

Route119_Text_CatherineRegister:
	.string "Do you have a Pokénav?\n"
	.string "It's a must-have tool for any TRAINER.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_CatherineRematchIntro:
	.string "How's your journey with Pokémon\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:
	.string "I'm still missing something…$"

Route119_Text_CatherinePostRematch:
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your Pokémon, your Pokémon\l"
	.string "rely on you.$"

Route119_Text_HughIntro:
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of Flight 77!$"

Route119_Text_HughDefeat:
	.string "Down and out!$"

Route119_Text_HughPostBattle:
	.string "The sheer exhilaration of\n"
	.string "American Airlines Flight 77.$"

Route119_Text_PhilIntro:
	.string "I'll show you the true potential of me\n"
	.string "and my S.A.M. salvo!$"

Route119_Text_PhilDefeat:
	.string "We lacked missiles…$"

Route119_Text_PhilPostBattle:
	.string "Ever since I was a little kid, I always\n"
	.string "admired shooting things out of the air…$"

Route119_Text_YasuIntro:
	.string "To lurk in forums, and live in\n"
	.string "a basement… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "I admit defeat!$"

Route119_Text_YasuPostBattle:
	.string "It's not even my own basement…$"

Route119_Text_TakashiIntro:
	.string "If you're not on your guard,\n"
	.string "you're in for some pain!$"

Route119_Text_TakashiDefeat:
	.string "I need some painkillers!$"

Route119_Text_TakashiPostBattle:
	.string "My surprise attack ended in\n"
	.string "a painful memory.$"

Route119_Text_HideoIntro:
	.string "To hide a tree, call the federal\n"
	.string "government of Brazil!$"

Route119_Text_HideoDefeat:
	.string "My last name is Kojima.\n"
	.string "Why do you ask?$"

Route119_Text_HideoPostBattle:
	.string "I have some solid gears made\n"
	.string "of metal.$"

Route119_Text_ChrisIntro:
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out these Gishkis!$"

Route119_Text_ChrisDefeat:
	.string "I don't have a clue about what it\n"
	.string "takes to Ritual Summon.$"

Route119_Text_ChrisPostBattle:
	.string "Go for a Surf on my Pokémon…\p"
	.string "Then fish off its back…\p"
	.string "Then crack my back.$"

Route119_Text_FabianIntro:
	.string "Hit me with a power cord!$"

Route119_Text_FabianDefeat:
	.string "Zap me!$"

Route119_Text_FabianPostBattle:
	.string "Hit me with another power cord!\n"
	.string "I can handle the voltage!$"

Route119_Text_DaytonIntro:
	.string "I swallow sludge\n"
	.string "to transform myself!$"

Route119_Text_DaytonDefeat:
	.string "I am going to\n"
	.string "enjoy an egg!$"

Route119_Text_DaytonPostBattle:
	.string "I heard all this from the\n"
	.string "Battle Frontier.$"

Route119_Text_RachelIntro:
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_RachelDefeat:
	.string "I'm looking for a pair of soles.$"

Route119_Text_RachelPostBattle:
	.string "Ach, my feet are killing me.$"

Route120_Text_ColinIntro:
	.string "Do you have any cards that can strike\n"
	.string "a Flying Elephant?$"

Route120_Text_ColinDefeat:
	.string "Attack for game!$"

Route120_Text_ColinPostBattle:
	.string "I lost at Pokémon, but I won\n"
	.string "the duel.$"

Route120_Text_RobertIntro:
	.string "My Pokémon is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:
	.string "Your Pokémon were stronger…$"

Route120_Text_RobertPostBattle:
	.string "A Pokémon that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRegister:
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my Pokénav!$"

Route120_Text_RobertRematchIntro:
	.string "A Pokémon that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your Pokémon are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "My Pokémon are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "Time to resolve Musical Sumo\n"
	.string "Dice Games!$"

Route120_Text_LorenzoDefeat:
	.string "What!? You negated my Musical Sumo\n"
	.string "Dice Games?$"

Route120_Text_LorenzoPostBattle:
	.string "I own 400 copies of Musical Sumo\n"
	.string "Dice Games.$"

Route120_Text_JennaIntro:
	.string "How's your physical fitness?$"

Route120_Text_JennaDefeat:
	.string "Fitness…$"

Route120_Text_JennaPostBattle:
	.string "Fitness what?$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "You play Clash of Clans?$"

Route120_Text_JeffreyDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I didn't upgrade my walls.$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll tryhard.$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a Pokénav…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious BUG Pokémon…$"

Route120_Text_JenniferIntro:
	.string "Pokémon have many special abilities.\n"
	.string "Then there's Truant.$"

Route120_Text_JenniferDefeat:
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:
	.string "The special abilities of Pokémon\n"
	.string "will make nuzlockers lose it.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "bags of chips?$"

Route120_Text_ChipDefeat:
	.string "What a disgraceful Doritos bag.$"

Route120_Text_ChipPostBattle:
	.string "Doesn't even contain Red 40.$"

Route120_Text_ClarissaIntro:
	.string "Why am I carrying this parasol?\p"
	.string "Rainy day, innit?$"

Route120_Text_ClarissaDefeat:
	.string "Forgot me parasol loicense…$"

Route120_Text_ClarissaPostBattle:
	.string "I don't think strong sunlight is good\n"
	.string "for my Pokémon.\l"
	.string "Wear sunscreen.$"

Route120_Text_AngelicaIntro:
	.string "Me, Pokémon, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "heads will fucking roll.$"

Route120_Text_AngelicaDefeat:
	.string "Well, I only have two of three…\n"
	.string "You know what happens now.$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol wouldn't suit you at all.\n"
	.string "Unless I whack you with it.$"

Route120_Text_KeigoIntro:
	.string "I will adopt the movements of Pokémon\n"
	.string "and create new Ninja combos.$"

Route120_Text_KeigoDefeat:
	.string "Damn, got handtrapped.$"

Route120_Text_KeigoPostBattle:
	.string "Perhaps I ought to apprentice under\n"
	.string "a pro player.$"

Route120_Text_RileyIntro:
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_RileyDefeat:
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_CallieIntro:
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_CallieDefeat:
	.string "Every warning has a story behind it.$"

Route120_Text_CalliePostBattle:
	.string "Do NOT feed the backend developers.$"

Route120_Text_LeonelIntro:
	.string "Do you have any infractions?$"

Route120_Text_LeonelDefeat:
	.string "I've seen tourney policy in action!$"

Route120_Text_LeonelPostBattle:
	.string "I think it's awesome you're so strong\n"
	.string "battling with the policy documents.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightful\n"
	.string "pretty bnuuy?$"

Route121_Text_VanessaDefeat:
	.string "My fucking bnuuy, man!$"

Route121_Text_VanessaPostBattle:
	.string "What will I do now?$"

Route121_Text_WalterIntro:
	.string "Hoy! Have you heard of the\n"
	.string "Eastern Kingdom of Mikado?$"

Route121_Text_WalterDefeat:
	.string "What in blazes?$"

Route121_Text_WalterPostBattle:
	.string "I'll end it thus!$"

Route121_Text_WalterRegister:
	.string "Your Pokémon prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my Pokémon, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your Pokémon and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are lines beyond our\n"
	.string "understanding in the world…\p$"

Route121_Text_TammyDefeat:
	.string "I have lost…$"

Route121_Text_TammyPostBattle:
	.string "Mt. Pyre…\n"
	.string "There is a mysterious story\l"
	.string "you can hear there…$"

Route121_Text_KateIntro:
	.string "Kate: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "Kate: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "Kate: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "Kate: If you've only got one Pokémon,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.\l"
	.string "Bullying is based, mind you.\n"
	.string "But only for shit opinions.$"

Route121_Text_JoyIntro:
	.string "Joy: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "Joy: Please forgive me, Kate!$"

Route121_Text_JoyPostBattle:
	.string "Joy: Ehehe, I'll have to train with Kate,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "Joy: You need at least two Pokémon\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "La Jinn turbo list!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I'll go bait more clowns on\n"
	.string "the subreddit.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious Pokémon grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more Pokémon at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Roast five Duelists a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're too good!$"

Route121_Text_CristinPostBattle:
	.string "Yee-yee ass haircut.$"

Route121_Text_CristinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your Pokénav!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see that I have all these\n"
	.string "cracked tiebreakers with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat:
	.string "Well, at least I'll make the bubble.$"

Route121_Text_CalePostBattle:
	.string "I bought too much stuff at\n"
	.string "the Lilycove Dept. Store.\p"
	.string "But hey, still a top cut record!$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's Pokémon!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "They're great, your Pokémon!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro:
	.string "I want everybody to see the Pokémon\n"
	.string "I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every Pokémon with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My Pokémon have never tasted defeat!\n"
	.string "On their next win, they'll taste\l"
	.string "ice cream!$"

Route121_Text_MarcelDefeat:
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I may have to train my gang some more\n"
	.string "before eating any sweet treats.$"

Route123_Text_WendyIntro:
	.string "Want to determine how based you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "I'm flying some colors myself!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of Gym Badges.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those stream highlights!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did someone else's content proud\n"
	.string "in that match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of sweat…$"

Route123_Text_VioletPostBattle:
	.string "Worst sweats are FPS players.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about cheating\n"
	.string "in Battle City.$"

Route123_Text_CameronDefeat:
	.string "Jinzo…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought Jinzo would carry…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your Pokénav.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your Pokémon\n"
	.string "develop psychic powers.\p"
	.string "They'll read your search history.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgor.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with Pokémon…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "Miu: Hello, Trainer. I hope your\n"
	.string "Pokémon won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "Miu: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "Miu: Trainer, your Pokémon are\n"
	.string "strong because you are the hero.$"

Route123_Text_MiuNotEnoughMons:
	.string "Miu: It's no fun to battle if you\n"
	.string "don't have two Pokémon.$"

Route123_Text_YukiIntro:
	.string "Yuki: Okay!\n"
	.string "We're beating the Trainer's Pokémon!$"

Route123_Text_YukiDefeat:
	.string "Yuki: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "Yuki: Why are you so strong?\n"
	.string "Oh, plot armor.$"

Route123_Text_YukiNotEnoughMons:
	.string "Yuki: It's no fun to battle if you\n"
	.string "don't have two Pokémon.$"

Route123_Text_KindraIntro:
	.string "Mt. Pyre…\n"
	.string "That bitch haunted.$"

Route123_Text_KindraDefeat:
	.string "I'm gonna haunt you.$"

Route123_Text_KindraPostBattle:
	.string "Mt. Pyre…\n"
	.string "Major spook factor…$"

Route123_Text_FernandoIntro:
	.string "I'll knock your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Agh!\n"
	.string "I'm gonna rip this sheet music!$"

Route123_Text_FernandoPostBattle:
	.string "Did you know there's a GBA song\n"
	.string "with a 29/16 time signature?$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome Bug Pokémon!\n"
	.string "Masuda-san got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "Masuda-san!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell him I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously bald!$"

Route123_Text_JazmynDefeat:
	.string "There goes my hair…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "What a load of shit.$"

Route123_Text_FrederickIntro:
	.string "Hello, there!$"

Route123_Text_FrederickDefeat:
	.string "General Kenobi.$"

Route123_Text_FrederickPostBattle:
	.string "Why am I reciting prequel memes?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, birds\n"
	.string "are my obsession!\p"
	.string "So, how could I not love\n"
	.string "Swallow's Nest into Barrier Statue?$"

Route123_Text_AlbertoDefeat:
	.string "That's a hard pill to swallow.$"

Route123_Text_AlbertoPostBattle:
	.string "They should unban all floodgates.$"

Route123_Text_EdIntro:
	.string "When there are no Duelists around,\n"
	.string "I playtest on Duelingbook.$"

Route123_Text_EdDefeat:
	.string "I kind of like DB judge calls.$"

Route123_Text_EdPostBattle:
	.string "I got frozen for 3 days.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a Trainer has\n"
	.string "activated my Mirror Force!$"

Route123_Text_JonasDefeat:
	.string "You couldn't be destroyed by\n"
	.string "card effects…$"

Route123_Text_JonasPostBattle:
	.string "I'm going to bait a weaker-looking\n"
	.string "player next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Percentages are for nerds.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my Pokémon,\n"
	.string "I can give some directions.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Mossdeep is east of here.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a Pokémon instead\n"
	.string "of swimming yourself…\p"
	.string "I'll knock you off!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "That didn't go well…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I need to go sunbathe.$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, Pokémon come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "Pokémon attack, and some just watch.\p"
	.string "It's a pretty terrible coinflip.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your Pokénav.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of bubbling…\n"
	.string "How about we draw?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "aiming to win!$"

Route124_Text_GracePostBattle:
	.string "Well, I guess I'm not making\n"
	.string "Day 2.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Activating Diva effect is my jam!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "Got Veiler'd…$"

Route124_Text_ChadPostBattle:
	.string "Diving requires Mossdeep's badge,\n"
	.string "if you're using a Pokémon.$"

Route124_Text_LilaIntro:
	.string "Lila: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "This Dragon Duel chump!$"

Route124_Text_LilaDefeat:
	.string "Lila: Roy! I told you to play\n"
	.string "Gravekeepers!$"

Route124_Text_LilaPostBattle:
	.string "Lila: Sigh…\p"
	.string "If only he knew how to actually\n"
	.string "use Royal Tribute…$"

Route124_Text_LilaNotEnoughMons:
	.string "Lila: You're planning to battle us?\n"
	.string "Not unless you have two Pokémon.$"

Route124_Text_RoyIntro:
	.string "Roy: My big sister is good at stun!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "Roy: Uh-oh…\n"
	.string "My sister will activate Summon Limit…$"

Route124_Text_RoyPostBattle:
	.string "Roy: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she always plays these\n"
	.string "lame strats.$"

Route124_Text_LilaRoyRegister:
	.string "Roy: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "Roy: Did you want to battle us?\n"
	.string "Bring two Pokémon, then.$"

Route124_Text_LilaRematchIntro:
	.string "Lila: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "Lila: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "Lila: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "Lila: You're planning to battle us?\n"
	.string "Not unless you have two Pokémon.$"

Route124_Text_RoyRematchIntro:
	.string "Roy: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "Roy: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "Roy: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with Pokémon later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "Roy: Did you want to battle us?\n"
	.string "Bring two Pokémon, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "Moist!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as Blue Tang…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady Swimmers\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer clown.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I'm not scared of clowns!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "Oh? You're approaching me?$"

Route125_Text_NolenDefeat:
	.string "I lost because you got closer.$"

Route125_Text_NolenPostBattle:
	.string "What? You expect some random guy to\n"
	.string "have a Stand cry?$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet Alien deck!$"

Route125_Text_StanDefeat:
	.string "My invasion failed…$"

Route125_Text_StanPostBattle:
	.string "Zer'oll just isn't good I guess.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a Scrap?$"

Route125_Text_TanyaDefeat:
	.string "I meant a Scrap card!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Mossdeep is south, right?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "Graydles I raised?$"

Route125_Text_SharonDefeat:
	.string "My theft of your cards failed…$"

Route125_Text_SharonPostBattle:
	.string "I love my slime bois.$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough player!\n"
	.string "I've braved the world's Tier 0s!$"

Route125_Text_ErnestDefeat:
	.string "You're Tier 0!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "Shoal Cave.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your Pokénav,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "Kim: A funny old man lives in the\n"
	.string "Shoal Cave. Someone told me.\l"
	.string "Why is he there?$"

Route125_Text_KimDefeat:
	.string "Kim: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "Kim: A funny old man lives in the\n"
	.string "Shoal Cave, doesn't he?\p"
	.string "Probably a Six Samurai!$"

Route125_Text_KimNotEnoughMons:
	.string "Kim: No, no, no! You need two Pokémon,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "Iris: Kim, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "Iris: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "Iris: Kim, are we really going into\n"
	.string "the Shoal Cave?\l"
	.string "There's Bushido Counters in there.$"

Route125_Text_IrisNotEnoughMons:
	.string "Iris: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a flight enthusiast\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "I don't know either.$"

Route125_Text_PresleyPostBattle:
	.string "Oh hey, a message in a bottle!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing Junk\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing Tuners into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly Synchron bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "fail a 15 minute solitaire combo!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I almost lost my fit!$"

Route126_Text_BarryPostBattle:
	.string "Why don't you get your fit rated?$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is Sootopolis.$"

Route126_Text_DeanDefeat:
	.string "MBT would be having a riot\n"
	.string "if he saw this.$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "Sootopolis. Must be underwater.$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "Damn! Do we even have any\n"
	.string "mermaid cards?$"

Route126_Text_NikkiPostBattle:
	.string "Guess I have to go to MtG.$"

Route126_Text_BrendaIntro:
	.string "I like to end games fast,\n"
	.string "so I play Numeron!$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!\n"
	.string "I went first!$"

Route126_Text_BrendaPostBattle:
	.string "I love Zexal!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm ripped like a Mystic Mine!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Too bad I didn't have Mine\n"
	.string "on my field.$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even bathe last year,\n"
	.string "I was too busy using Zodiac Duelist.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, using Facebook didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "Git gud.$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "A failed heart transplant!$"

Route126_Text_SiennaPostBattle:
	.string "What? This is my Crystal Heart.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "WOW.$"

Route127_Text_CamdenPostBattle:
	.string "Well, at least I could win in\n"
	.string "a race.$"

Route127_Text_DonnyIntro:
	.string "Do you have a deck whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "My least favorite deck?\n"
	.string "Easily Hazy Flame.$"

Route127_Text_JonahIntro:
	.string "Through Tistina gameplay, I have\n"
	.string "attained a state of serenity…$"

Route127_Text_JonahDefeat:
	.string "Though I have lost, my Tistinas\n"
	.string "remain calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I recall nothing.\n"
	.string "The line remains in the video…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I snagged\n"
	.string "a Surfing Pokémon?$"

Route127_Text_HenryDefeat:
	.string "Guess I'm swimming in it!$"

Route127_Text_HenryPostBattle:
	.string "It'd be a handful if I hooked\n"
	.string "your tough Pokémon!$"

Route127_Text_RogerIntro:
	.string "Well, hey! You're in the presence\n"
	.string "of an Icejade enthusiast!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:
	.string "Look, I just think Icejades are neat.$"

Route127_Text_AidanIntro:
	.string "Do you have what it takes to beat the\n"
	.string "weakest Penguin enjoyer?$"

Route127_Text_AidanDefeat:
	.string "Yepenguin.$"

Route127_Text_AidanPostBattle:
	.string "Penguins are just little guys.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet.$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "My feet!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match. I need to think.$"

Route127_Text_AthenaDefeat:
	.string "Ahh! I would have won in time!$"

Route127_Text_AthenaPostBattle:
	.string "All that stalling for nothing.$"

Route128_Text_IsaiahIntro:
	.string "This triathlon is tough.$"

Route128_Text_IsaiahDefeat:
	.string "You're tough too…$"

Route128_Text_IsaiahPostBattle:
	.string "Rough and tough.\n"
	.string "That's my style.$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your Pokénav.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's like playing U.A.$"

Route128_Text_KatelynDefeat:
	.string "Midfielder effect?$"

Route128_Text_KatelynPostBattle:
	.string "I need more Field Spells.$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the Pokémon CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A Pokémon battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "Shoutout to Icarus Attack and its\n"
	.string "variants.\p"
	.string "Gotta be one of my favorite designs.$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "You're indestructible!$"

Route128_Text_AlexaPostBattle:
	.string "My favorite Icarus Attack analogue?\n"
	.string "Offerings to the Snake Deity.\l"
	.string "Because I am a lizard.$"

Route128_Text_RubenIntro:
	.string "Tearlaments strongest!$"

Route128_Text_RubenDefeat:
	.string "Bro ban Shifter for real.$"

Route128_Text_RubenPostBattle:
	.string "Tearlaments weakest.$"

Route128_Text_WayneIntro:
	.string "I want to visit Ever Grande.\n"
	.string "The Pokémon League is up there.$"

Route128_Text_WayneDefeat:
	.string "You're out of my league!$"

Route128_Text_WaynePostBattle:
	.string "Ah, right. You need to beat the\n"
	.string "Gym in Sootopolis to get there.$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "Blackbeard effect?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I tried to equip and failed.$"

Route128_Text_HarrisonPostBattle:
	.string "I wish I could search Shipyarrrd\n"
	.string "more consistently.$"

Route128_Text_CarleeIntro:
	.string "Sunlight Wolf seems to be more used\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "You banished my Spinny!$"

Route128_Text_CarleePostBattle:
	.string "Let me end on a Nibiru token.$"

Route129_Text_ChaseIntro:
	.string "Going to my first YCS.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Hopefully it goes better than this…$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "make it to Table 500.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Post-run thighs.$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "I gotta side out first!$"

Route129_Text_ReedDefeat:
	.string "Man, even my side deck didn't help.$"

Route129_Text_ReedPostBattle:
	.string "There's no prizing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "Alright! Time to show off my\n"
	.string "Suship deck!$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to enjoy some sushi…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why early scooping can be\n"
	.string "really useful.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarencePostBattle:
	.string "Balling isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a trader out in the sea.\p"
	.string "I think we should pack battle!$"

Route130_Text_RodneyDefeat:
	.string "Those packs were crazy…$"

Route130_Text_RodneyPostBattle:
	.string "They'll put me on a pack watch\n"
	.string "at this rate.$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Ack! My blue heart was my\n"
	.string "G Golem Crystal Heart!$"

Route130_Text_KatiePostBattle:
	.string "I wish G Golems were good.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "I'm like I'm on Peaceful difficulty.$"

Route130_Text_SantiagoDefeat:
	.string "I should have been on Peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "Multitasking at its finest…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with Pokémon.\n"
	.string "This seems like a terrible idea.$"

Route131_Text_RichardDefeat:
	.string "Ouch! I think there's something\n"
	.string "near my leg!$"

Route131_Text_RichardPostBattle:
	.string "Ah…\n"
	.string "Just some seaweed.$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "I'm bored of the sea, and of\n"
	.string "the men in it.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "That's a bitter pill to swallow.$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "Why doesn't he just get out of\n"
	.string "the water, then?$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "Reli: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "Reli: We couldn't win even though we\n"
	.string "tagged up…$"

Route131_Text_ReliPostBattle:
	.string "Reli: Things are more fun when you\n"
	.string "tag with someone else.$"

Route131_Text_ReliNotEnoughMons:
	.string "Reli: You don't have two Pokémon?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "Ian: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "Ian: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "Ian: You know how Pacifidlog is\n"
	.string "a floating town?\p"
	.string "Pretty rad.$"

Route131_Text_IanNotEnoughMons:
	.string "Ian: If you have two Pokémon,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd tower nearby.\p"
	.string "Most trainers using Fly to get around\n"
	.string "tend to stay away from it.$"

Route131_Text_KevinIntro:
	.string "The people of Pacifidlog are\n"
	.string "a peaceful bunch.\p"
	.string "There's a really strong Trainer\n"
	.string "visiting, from what I heard.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Who is the Trainer?\n"
	.string "Sorry, I don't know myself.$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid. Now I catch hands.$"

Route132_Text_GilbertDefeat:
	.string "My Sylvan deck failed…$"

Route132_Text_GilbertPostBattle:
	.string "HAT format can get a little stale\n"
	.string "sometimes, y'know?$"

Route132_Text_DanaIntro:
	.string "I try not to swim where people use\n"
	.string "Concentrating Current.$"

Route132_Text_DanaDefeat:
	.string "No, not July 2018 Duel Links format!$"

Route132_Text_DanaPostBattle:
	.string "I refuse to play against\n"
	.string "Cipher Soldier again…$"

Route132_Text_RonaldIntro:
	.string "Bro are you on Windows?\n"
	.string "You should use Linux.$"

Route132_Text_RonaldDefeat:
	.string "Play Noita.$"

Route132_Text_RonaldPostBattle:
	.string "Honestly, a Steam Deck is a\n"
	.string "banger investment.$"

Route132_Text_KiyoIntro:
	.string "Hoo-hah!\n"
	.string "I practice Gate Guardian daily!$"

Route132_Text_KiyoDefeat:
	.string "Hoo-hah!\n"
	.string "I got stonewalled!$"

Route132_Text_KiyoPostBattle:
	.string "Hoo-hah!\n"
	.string "If you use Gate Guardian cards\l"
	.string "for FTKs, you are cringe!$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Haha! You shall become fodder\n"
	.string "for my Kaiju strategy!$"

Route133_Text_FranklinDefeat:
	.string "Whoa! My Waterfront!$"

Route133_Text_FranklinPostBattle:
	.string "I need Kaiju Counters, man…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I'm a Gusto player…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "When… you can…$"

Route133_Text_LindaIntro:
	.string "What Attribute do I use?\n"
	.string "All of them!$"

Route133_Text_LindaDefeat:
	.string "I couldn't use all my Attributes\n"
	.string "well enough.$"

Route133_Text_LindaPostBattle:
	.string "Hm? What am I playing?\n"
	.string "Elementsabers, of course!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't cheat like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too fair!$"

Route133_Text_WarrenPostBattle:
	.string "Everyone else stacks their decks,\n"
	.string "I'm sure of it.$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "Harpie strats today.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to Fortree, but\n"
	.string "there's a regional in Slateport soon.$"

Route133_Text_MollieIntro:
	.string "We lived during the OCG's Exodia\n"
	.string "format of '99. We're tough!$"

Route133_Text_MollieDefeat:
	.string "We couldn't draw enough.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "experience true Tier 0.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the banlist. They need legacy formats.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of format.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "I only play the best Water deck.\n"
	.string "Aquaactress!$"

Route134_Text_JackDefeat:
	.string "That was a flop.$"

Route134_Text_JackPostBattle:
	.string "Yeah, Aquaactress doesn't really\n"
	.string "do anything, actually.$"

Route134_Text_LaurelIntro:
	.string "I'm heading to Slateport regionals.$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "Wait, did I register online already?$"

Route134_Text_AlexIntro:
	.string "Do you like setting backrow?\n"
	.string "My Dark Simorgh doesn't!$"

Route134_Text_AlexDefeat:
	.string "My birds! Aargh!$"

Route134_Text_AlexPostBattle:
	.string "My Simorghs run dry quickly after\n"
	.string "a long game…$"

Route134_Text_HitoshiIntro:
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "No need for words. You have won.$"

Route134_Text_AaronIntro:
	.string "Hey, uh… mind if you help me\n"
	.string "record part of my YCS vlog?$"

Route134_Text_AaronDefeat:
	.string "Well, I might have to cut that.$"

Route134_Text_AaronPostBattle:
	.string "I want to get some nice B-roll.$"

Route134_Text_KelvinIntro:
	.string "Some Atlanteans nearly sank my boat!$"

Route134_Text_KelvinDefeat:
	.string "I even saw Poseidra!$"

Route134_Text_KelvinPostBattle:
	.string "I know a fainted Pokémon\n"
	.string "can still Surf, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your Pokémon dodge my\n"
	.string "lightning-quick judge call?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for having\n"
	.string "a judge clarify something.$"

Route134_Text_ReynaIntro: @
	.string "Alright! No Jinzos around!\n"
	.string "Paleos are a go!$"

Route134_Text_ReynaDefeat:
	.string "But… my Trap deck…$"

Route134_Text_ReynaPostBattle:
	.string "Maybe I should mix it with\n"
	.string "Tear after all.$"

Route134_Text_HudsonIntro:
	.string "Oh, no, I'm not going to any events.\n"
	.string "But I will be taking you down!$"

Route134_Text_HudsonDefeat:
	.string "That didn't go quite as planned.$"

Route134_Text_HudsonPostBattle:
	.string "You're pretty good. Maybe you could\n"
	.string "get a top cut profile about you.$"
