PacifidlogTown_BakuraHouse_MapScripts::
	.byte 0

PacifidlogTown_BakuraHouse_EventScript_Plaguey::
	msgbox PacifidlogTown_BakuraHouse_Text_Husband, MSGBOX_NPC
	end

PacifidlogTown_BakuraHouse_EventScript_SMT::
	msgbox PacifidlogTown_BakuraHouse_Text_SCPStuff, MSGBOX_SIGN
	end

PacifidlogTown_BakuraHouse_Text_SCPStuff:
	.string "So many fucking tabs open…\p"
	.string "An SCP article, an N/R spreadsheet…\p"
	.string "Not even going to question what\n"
	.string "that is…\p"
	.string "Oh, a pirated copy of Shin Megami\n"
	.string "Tensei V.\p"
	.string "Probably best to just leave it.$"

PacifidlogTown_BakuraHouse_Text_Husband:
	.string "Hi there!\n"
	.string "My husband's not around right now.\p"
	.string "He's busy handling stuff in\n"
	.string "Ever Grande.$"

